### ISSUE TITLE
Swoole\Process->exit 方法命名错误

### ISSUE THREAD

**Issue by NHZEX** [swoft-cloud/swoole-ide-helper#9]
https://github.com/swoft-cloud/swoole-ide-helper/blob/9de6d57310df0e533ffc6027cb54f06287f4b599/src/namespace/Process.php#L138

**Comment by NHZEX** [comment]
在补充一个：
https://github.com/swoft-cloud/swoole-ide-helper/blob/6d813bd31cd18924771181922bf3bc0b92ae68b7/src/namespace/Event.php#L75

**Comment by inhere** [comment]
已修复
